import{a as f,S as y,i}from"./assets/vendor-D1eTGYtO.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();async function h(o,r=1,s=15){const a="https://pixabay.com/api/",e="45282736-76f00277f987f73abb95d9f87";try{return(await f.get(a,{params:{key:e,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:s}})).data}catch(t){throw console.error("Error fetching images:",t),t}}function m(o){const r=new y(".gallery a",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250}),s=document.querySelector(".gallery"),a=o.hits.map(e=>`<div class="image-wrapper">
    <a href="${e.largeImageURL}">
    <img class="gallery-images" src="${e.webformatURL}" alt="${e.tags}"></img>
    </a>
    <div class="text-wrapper">
    <div class="text-item"><h5 class="text-header">Likes</h5><p class="text-info">${e.likes}</p></div>
    <div class="text-item"><h5 class="text-header">Views</h5><p class="text-info">${e.views}</p></div>
    <div class="text-item"><h5 class="text-header">Comments</h5><p class="text-info">${e.comments}</p></div>
    <div class="text-item"><h5 class="text-header">Downloads</h5><p class="text-info">${e.downloads}</p></div>
    </div>
    </div>`).join("");s.insertAdjacentHTML("beforeend",a),r.refresh()}function g(o){const r=document.querySelector(".gallery");r.innerHTML=""}const p=document.querySelector(".search-form"),c=document.querySelector(".loader"),v=document.querySelector(".input-text");p.addEventListener("submit",L);let n=1,d="";async function L(o){o.preventDefault();const r=v.value.trim().toLowerCase();if(r===""){i.error({position:"topRight",message:"Search query cannot be empty. Please enter a keyword!"});return}d=r,n=1,g(),c.classList.remove("hidden"),document.querySelector(".load-more").classList.add("hidden");try{const s=await h(d,n);s.total===0?i.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}):(m(s),s.totalHits>15&&document.querySelector(".load-more").classList.remove("hidden"))}catch(s){i.error({position:"topRight",message:"An error occurred while fetching data. Please try again later."}),console.error(s)}finally{c.classList.add("hidden")}p.reset()}const u=document.querySelector(".load-more");u.addEventListener("click",async()=>{n+=1,c.classList.remove("hidden");try{const o=await h(d,n);m(o);const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*20,behavior:"smooth"}),n*15>=o.totalHits&&(u.classList.add("hidden"),i.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."}))}catch(o){i.error({position:"topRight",message:"An error occurred while loading more images."}),console.error(o)}finally{c.classList.add("hidden")}});
//# sourceMappingURL=commonHelpers.js.map
